### ISSUE TITLE
I could not see the FSL scripts in http://github.com/npnl/LI_FSL

### ISSUE THREAD

**Issue by jbpoline** [npnl/LI-FSL#7]
Hi, 
- I liked this work: it would be useful if a matlab license is an issue.
- I saw that in your report you state that "Our scripts for these calculations may be found online at http://chan.usc.edu/npnl/resources."  and went to this address. I then saw : 

GITHUB

NPNL GitHub
ENIGMA Wrapper Scripts
Laterality Index (LI)
ASL Processing Tips
DTI Processing Tips
T2 Maps
Read-Logfiles
AFNI MRI Analysis
SPM MRI Analysis
PyMVPA
Brain Voyager MRI Analysis
FSL MRI Analysis

NEUROIMAGING TOOLS
NITRC
AFNI
FSL
NIPY

OPEN SOURCE NEUROSCIENCE & DATA SHARING
Open Neuroscience
INDI Database
The Human Connectome
Neurosynth
BrainHack

I checked  the two most promising: Laterality Index (LI) and  FSL-MRI-Analysis but could not find the scripts to review and test them. Did I miss something ? apologies if I did. Also, is there an example dataset to test ?
- Other minor issues; you could discuss/implement the threshold free index that have been proposed, most recently in http://www.ncbi.nlm.nih.gov/pubmed/26846561
- minor as well: github does not render the table well. Not sure if there is an easy firx for that.

**Comment by npnl** [comment]
Thank you for your helpful comments and drawing our attention to several things to fix. We have responded to them here:

• I saw that in your report you state that "Our scripts for these calculations may be found online at http://chan.usc.edu/npnl/resources." and went to this address. I checked the two most promising: Laterality Index (LI) and FSL-MRI-Analysis but could not find the scripts to review and test them. Did I miss something? apologies if I did. Also, is there an example dataset to test?

-->We thank the reviewer for pointing this out. We had the some of our scripts in a separate branch; however, now we have placed the scripts in a zipped folder on our brainhack page (https://github.com/npnl/LI-FSL) and have updated this in our markdown document (https://github.com/npnl/LI-FSL/blob/master/LI_Abstract/README.md). 

To note: Currently, our scripts run in bash and in matlab; we are working on stream-lining our script into a script that uses python and bash, and will update the package on github in a couple of weeks once it is complete. We cannot put data online for testing but could provide data by request if emailed. We have, however, put some sample folders to demonstrate the file structure needed for the script to run (https://github.com/npnl/LI-FSL)

• Other minor issues; you could discuss/implement the threshold free index that have been proposed, most recently in http://www.ncbi.nlm.nih.gov/pubmed/26846561

--> We appreciate this helpful advice. We have now reflected this change in the conclusion of our document.

• minor as well: github does not render the table well. Not sure if there is an easy fix for that.

-->We agree with the reviewer; however this seems to look ok once converted to the pdf version. For simplicity, we have now saved the table as a jpeg image and uploaded the file here as well: https://github.com/npnl/LI-FSL/blob/master/LI_Abstract/lli08ra.jpg
